SETTING_FILENAME = "filename"
SETTING_RECENT_FILES = "recentFiles"
SETTING_WIN_SIZE = "window/size"
SETTING_WIN_POSE = "window/position"
SETTING_WIN_GEOMETRY = "window/geometry"
SETTING_LINE_COLOR = "line/color"
SETTING_FILL_COLOR = "fill/color"
SETTING_ADVANCE_MODE = "advanced"
SETTING_WIN_STATE = "window/state"
SETTING_SAVE_DIR = "savedir"
SETTING_PAINT_LABEL = "paintlabel"
SETTING_LAST_OPEN_DIR = "lastOpenDir"
SETTING_AUTO_SAVE = "autosave"
SETTING_SINGLE_CLASS = "singleclass"
FORMAT_PASCALVOC = "PascalVOC"
FORMAT_YOLO = "YOLO"
FORMAT_CREATEML = "CreateML"
SETTING_DRAW_SQUARE = "draw/square"
SETTING_LABEL_FILE_FORMAT = "labelFileFormat"

# Assistant settings (Phase 0/1 scaffolding)
SETTING_ASSISTANT_ENABLED = "assistant/enabled"
SETTING_ASSISTANT_AUTO_PREDICT = "assistant/autoPredict"
SETTING_ASSISTANT_CONF = "assistant/confidence"
SETTING_ASSISTANT_IOU = "assistant/iou"
SETTING_ASSISTANT_BOOTSTRAP_IMAGES = "assistant/bootstrapImages"
SETTING_ASSISTANT_MAX_TRAIN_IMAGES = "assistant/maxTrainImages"
SETTING_ASSISTANT_EPOCHS = "assistant/epochs"
SETTING_ASSISTANT_LAST_MODEL_PATH = "assistant/lastModelPath"
SETTING_ASSISTANT_MODEL_NAME = "assistant/modelName"
SETTING_ASSISTANT_IMGSZ = "assistant/imgsz"

DEFAULT_ENCODING = "utf-8"
